#' Add a spanner to a gt table
#'
#' Adds a spanner header over selected columns in a `gt` table. Optionally, an empty column can be inserted before the first selected column.
#'
#' @param gt_table A `gt` table object.
#' @param spanner_name Character string giving the label for the spanner.
#' @param selection_type Character string defining the selection method passed to `tidyselect_gt_column_name()` (e.g., `"contains"`, `"starts_with"`).
#' @param columns Column selection pattern to identify which columns to span.
#' @param add_empty Logical; if `TRUE`, adds an empty column before the first spanned column. Defaults to `TRUE`.
#'
#' @return A modified `gt` table with a spanner header (and optional empty column) added.
#' @export
#'
#' @examples
#' \dontrun{
#' gt_tbl <- gt::gt(head(mtcars))
#' add_gt_spanner(gt_tbl, "Performance", selection_type = "contains", columns = "hp")
#' }
add_gt_spanner <- function(
    gt_table,
    spanner_name,
    selection_type,
    columns,
    add_empty = TRUE
) {
  column_names <- gt_table |>
    tidyselect_gt_column_name(
      selection_type = selection_type,
      columns = columns
    )
  gt <- gt_table |>
    tab_spanner(label = spanner_name, columns = column_names) |>
    style_gt_spanner(font_size = "size_base")

  if (add_empty) {
    random_suffix <- as.integer(runif(1, 0, 1e4))
    empty_name <- glue("empty{random_suffix}")
    first_column <- column_names[1]
    gt <- gt |> cols_add({{ empty_name }} := NA, .before = first_column)
  }

  return(gt)
}

#' Add a total grand summary row to a gt table
#'
#' Adds a "Total" grand summary row to selected columns of a `gt` table using configuration from `make_gt_config()`.
#'
#' @param gt_table A `gt` table object.
#' @param selection_type Character string defining the selection method passed to `tidyselect_gt_column_name()`. Defaults to `"contains"`.
#' @param labels A configuration list generated by `make_gt_labels()` that defines which columns to summarize and ignore.
#'
#' @return A modified `gt` table with a grand summary "Total" row.
#' @export
#'
#' @examples
#' \dontrun{
#' labels <- make_gt_labels()
#' gt_tbl <- gt::gt(head(mtcars))
#' add_gt_grand_summary_row_total(gt_tbl, labels = labels)
#' }
add_gt_grand_summary_row_total <- function(
  gt_table,
  selection_type = "contains",
  labels
) {

  columns_select <- gt_table |>
    tidyselect_gt_column_name(
      selection_type = selection_type,
      columns = labels$summarize_cols_total
    )

  columns_ignore <- gt_table |>
    tidyselect_gt_column_name(
      selection_type = selection_type,
      columns = labels$ignore_cols
    )

  gt <- gt_table |>
    grand_summary_rows(
      columns = columns_select,
      fns = list("Total" = ~ sum(.)),
      fmt = list(~ gt::fmt_integer(., columns = columns_select))
    ) |>
    style_gt_grand_summary_row() |>
    grand_summary_rows(
      columns = columns_ignore,
      fns = list("Total" = ~NA_character_),
      fmt = ~ sub_missing(., missing_text = "")
    )

  return(gt)
}

#' Add a mean grand summary row to a gt table
#'
#' Adds a "Mean" grand summary row to selected columns of a `gt` table using configuration from `make_gt_config()`.
#'
#' @param gt_table A `gt` table object.
#' @param selection_type Character string defining the selection method passed to `tidyselect_gt_column_name()`. Defaults to `"contains"`.
#' @param labels A configuration list generated by `make_gt_labels()` that defines which columns to summarize and ignore.
#'
#' @return A modified `gt` table with a grand summary "Mean" row.
#' @export
#'
#' @examples
#' \dontrun{
#' labels <- make_gt_labels()
#' gt_tbl <- gt::gt(head(mtcars))
#' add_gt_grand_summary_row_mean(gt_tbl, labels = labels)
#' }
add_gt_grand_summary_row_mean <- function(
  gt_table,
  selection_type = "contains",
  labels
) {
  columns_percent <- gt_table |>
    tidyselect_gt_column_name(
      selection_type = selection_type,
      columns = labels$format_cols_percent
    )
  columns_integer <- gt_table |>
    tidyselect_gt_column_name(
      selection_type = selection_type,
      columns = labels$format_cols_integer
    )
  columns_number <- gt_table |>
    tidyselect_gt_column_name(
      selection_type = selection_type,
      columns = labels$format_cols_percent
    )
  columns_select <- gt_table |>
    tidyselect_gt_column_name(
      selection_type = selection_type,
      columns = labels$summarize_cols_mean
    )
  columns_ignore <- gt_table |>
    tidyselect_gt_column_name(
      selection_type = selection_type,
      columns = labels$ignore_cols
    )

  gt <- gt_table |>
    grand_summary_rows(
      columns = columns_select,
      fns = list("Mean" = ~ mean(.)),
      fmt = list(
        ~ gt::fmt_integer(., columns = c(columns_integer, columns_number)),
        ~ gt::fmt_percent(., columns = columns_percent, decimals = 0)
      )
    ) |>
    style_gt_grand_summary_row() |>
    grand_summary_rows(
      columns = columns_ignore,
      fns = list("Mean" = ~NA_character_),
      fmt = ~ sub_missing(., missing_text = "")
    )

  return(gt)
}
